---
title: "cRDA analysis"
output: html_notebook
---

Load libraries
```{r}
library("vegan")
library("psych")
library("edgeR")
library("ggpubr")
library("extrafont")
```

Load functions
```{r}
setwd("")
source("RDAfunctions.R")
```

Load trimmed table of counts
```{r}
data <- t(as.matrix(read.table("dataFileredCounts.txt",header= T, row.names = 1)))
```

Define variables ecotype and ecotype pair 
```{r}
# Ecotype
ecotype <- c(rep("A",12),rep("M",12))

# Ecotype pairs
locality <- c(rep("1",3),rep("3",3),rep("4",3),rep("5",3),
              rep("1",3),rep("3",3),rep("4",3),rep("5",3))
```

Build a table of explanatory variables
```{r}
env = makeEnv(ecotype, locality, data)
```

Perform cRDA analysis
```{r}
helio.rda <- helio_rda(cpm(data), env)
```

Check significance of the model
```{r}
vif.cca(helio.rda) #check variance inflation factors for the predictor variables used in the model
signif.full <- anova.cca(helio.rda, parallel=getOption("mc.cores"),
                         permutations = how(nperm=1000))
signif.axis <- anova.cca(helio.rda, by="axis", step=10)
signif.full
signif.axis 

scores_helio.rda <- scores(helio.rda)$species
write.table(x = scores_helio.rda, "score_RDA1_cond.txt", sep="\t")
```

Plot RDA
```{r}
alpha <- 0.18
plot_rda(helio.rda)
```

Transform RDA scores into z-scores
```{r}
zrda = rda2zscore("score_RDA1_cond.txt")
write.table(x = zrda, "Zscore_RDA1_cond_expr.txt", sep="\t", row.names = T, quote = F)
```

Identify candidate outliers
```{r}
candidates.05 <- outliers(scores_helio.rda[,1],2) 
candidates.01 <- outliers(scores_helio.rda[,1],2.6) 
ncand.05 <- length(candidates.05)
ncand.01 <- length(candidates.01)
print(paste0("The number of candidate loci (p < 0.05) is: ",ncand.05))
print(paste0("The number of candidate loci (p < 0.01) is: ",ncand.01))

candidates.05 = rda_out(candidates.05) # prints output totable
```




